//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlants.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public string PlantId { get; set; }
        public string PlantName { get; set; }
        public string PlantType { get; set; }
        public string PlantOrigin { get; set; }
    }
}
